### ISSUE TITLE
Link to walkthrough is broken

### ISSUE THREAD

**Issue by Brontojoris** [adobe/reactor-postman#10]
### Expected Behaviour

Clicking the [walkthrough link](https://developer.adobelaunch.com/guides/extensions/getting-started/#create-an-adobe-io-technical-account) in the [Adobe I/O integration](https://github.com/adobe/reactor-postman#adobe-io-integration) paragraph takes me to the correct page.

### Actual Behaviour

Clicking the link takes me to a 404 error page.

**Comment by thebenrob** [comment]
@adobe export issue to Jira project PDCL
