### ISSUE TITLE
error: oauth-token is not valid

### ISSUE THREAD

**Issue by CalmBaker** [adobe/reactor-postman#8]
{
    "errors": [
        {
            "status": "401",
            "code": "oauth-token-invalid",
            "title": "Oauth token is not valid",
            "meta": {
                "request_id": "1j9gtngUef4FLp8rG3ARSAhMgThuYhQ7"
            }
        }
    ]
}

While creating a property, got the above error. Please fix this issue. All the credentials are correct.

**Comment by jbarchibald** [comment]
Can you give me more info as to what request you were trying to make, and also what exactly did you do to obtain the access token,  (the reason i ask is there are a number of different ways the access token can be obtained)

**Comment by thebenrob** [comment]
Due to lack of response, I'm going to close this out to keep things clean.  Please reopen the issue if you still need help.
