### ISSUE TITLE
Method to automate Launch deployments

### ISSUE THREAD

**Issue by DavidLozzi** [adobe/reactor-postman#9]
Hello!

Thanks for this postman project, I'll be downloading and exploring. I am wondering if Adobe has any other repos that can help us automate our launch/analytics configuration? We'd like to have the developers handle creating the configs through JSON, and our deployment pipelines (CI/CD) handle creating the artifacts in Launch. Also, as we deploy env to env that would be automated as well.

I see all of the APIs exist, which is awesome, I'm hoping for some head start in this area.

**Comment by jeffchasin** [comment]
Hey @DavidLozzi,

Here are some other resources you may find useful:

* [Launch Developer Documentation](https://developer.adobelaunch.com/)
* [Why build an extension?](https://youtu.be/0ToAf0M8QYg)
* [Extension Development Quickstart Guide](https://developer.adobelaunch.com/extensions/guides/quickstart/)
* [Extension Development Demo Video](https://youtu.be/rxjtC9o4rl0)
* [Join the Developer Slack Community](http://join.launchdevelopers.chat)
* [Adobe Technical Blog](https://medium.com/adobetech)

**Webinars** (previously recorded):

* 09/27/2018: <https://my.adobeconnect.com/p2k5f4hx57y1>
* 11/01/2018: <https://my.adobeconnect.com/pq933yjn1nuo>
* 01/24/2019: <https://my.adobeconnect.com/p3fx3wjp55iu>
* 04/17/2019: <https://my.adobeconnect.com/pn4vzrthlc4x>

**Open Source Stuff**:

* [Launch Core Extension](https://github.com/adobe/reactor-extension-core)
* [Turbine Client-side Library](https://www.npmjs.com/package/@adobe/reactor-turbine)
* [Hello World Example Extension](https://github.com/adobe/reactor-helloworld-extension)
* [Hotjar Example Extension](https://github.com/adobe/reactor-hotjar-extension)

**Tools**:

* [Scaffold Tool](https://www.npmjs.com/package/@adobe/reactor-scaffold)
* [Sandbox Utility](https://www.npmjs.com/package/@adobe/reactor-sandbox)
* [Packager Utility](https://www.npmjs.com/package/@adobe/reactor-packager)
* [Releaser Utility](https://www.npmjs.com/package/@adobe/reactor-releaser)
* [Downloader Utility](https://www.npmjs.com/package/@adobe/reactor-downloader)
* [Uploader Utility](https://www.npmjs.com/package/@adobe/reactor-uploader)
* [Sync Utility](https://www.npmjs.com/package/@adobe/reactor-sync)
* [JavaScript SDK](https://www.npmjs.com/package/@adobe/reactor-sdk)
* [Postman Collection](https://github.com/adobe/reactor-postman)

**Comment by DavidLozzi** [comment]
Wow, thank you for the comprehensive list of resources! I've seen some of this already, and maybe I have a more fundamental question: is what I'm looking to do an extension? I don't necessarily want to integrate anything _into_ Launch, just want to use the APIs to `post` info and `get` info.

**Comment by DavidLozzi** [comment]
react-sync looks promising, chasing this down ;)
